isp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", RedirectView.as_view(url="kuhub/")),
    path("admin/", admin.site.urls),
    path("kuhub/", include("kuhub.urls")),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

kuhub/urls.py
"""Import path from django"""
from django.urls import path, re_path
from django.views.generic import RedirectView
from kuhub import views


app_name = "kuhub"
urlpatterns = [
    path('', RedirectView.as_view(url="review-hub/")),
    path('review-hub/', views.ReviewHubView.as_view(), name='review'),
    path('summary-hub/', views.SummaryHubView.as_view(), name='summary'),
    path('tricks-hub/', views.TricksHubView.as_view(), name='tricks'),
    path('group-hub/', views.GroupView.as_view(), name='groups'),
    path('home', views.HomePageView.as_view(), name='home'),
    path('<int:pk>/group', views.GroupDetail.as_view(), name='group_detail'),
    path('<int:group_id>/group-event-create', views.GroupEventController.group_event_create, name='group_event'),
    path('<int:group_id>/note', views.GroupEventController.add_note, name='group_note'),
    path('<int:note_id>/note/delete', views.GroupEventController.delete_note, name='note_delete'),
    path('<int:group_id>/task', views.GroupEventController.add_task, name='group_task'),
    path('<int:note_id>/task/delete', views.GroupEventController.delete_task, name='task_delete'),
    path('<int:task_id>/task/change_status', views.GroupEventController.change_task_status, name='change_task_status'),
    path('<int:task_id>/task/assign_event', views.GroupEventController.assign_task_in_event, name='assign_task_event'),
    path('<int:task_id>/task/unassign_event', views.GroupEventController.unassign_task, name='unassign_task_event'),
    path('<int:event_id>/delete', views.GroupEventController.group_event_delete, name='event_delete'),
    path('<int:pk>/event', views.EventDetail.as_view(), name='event_detail'),
    path('create-group/', views.GroupFeature.create_group, name='create_group'),
    path('<int:group_id>/join', views.GroupFeature.join, name='join'),
    path('liked/', views.post_feature_view.like_post, name='like_post'),
    path('disliked/', views.post_feature_view.dislike_post, name='dislike_post'),
    path('create-post/', views.PostFeature.create_post, name='create_post'),
    path('profile/settings/', views.ProfileSetting.profile_settings, name='profile_settings'),
    path('profile/<str:username>/', views.ProfileView.profile_view, name='profile_view'),
    path('toggle-follow/<int:user_id>/', views.ProfileView.toggle_follow, name='toggle_follow'),
    path('followers/', views.FollowView.followers_page, name='followers_page'),
    path('following/', views.FollowView.following_page, name='following_page'),
    path('gen-ed-list/', views.GenEdTypeListView.as_view(), name='gen_ed_type_list'),
    path('subject/<str:course_code>/', views.SubjectDetailView.as_view(), name='subject_detail'),
    path('post/<int:pk>/', views.PostFeature.post_detail, name='post_detail'),
    path('post/<int:pk>/edit/', views.PostFeature.edit_post, name='edit_post'),
    path('report/<int:pk>/', views.post_feature_view.report_post, name='report_post'),
    re_path(r'^.*/$', RedirectView.as_view(url='/kuhub/review-hub/'), name='redirect_to_review_hub'),
]

kuhub/models/group.py
from django.db import models
import datetime
from django.utils import timezone

class Group(models.Model):
    group_name = models.CharField(max_length=200)
    group_member = models.ManyToManyField('auth.User')
    group_tags = models.ManyToManyField('GroupTags')
    group_description = models.CharField(max_length=255)
    create_date = models.DateField(default=datetime.date.today)
    group_password = models.OneToOneField('GroupPassword', on_delete=models.CASCADE, null=True, blank=True)

    def was_published_recently_post(self):
            """
            Checks if the post was published recently.

            Returns:
                bool: True if the post was published within the last day.
            """
            now = timezone.now().date()
            return now - datetime.timedelta(days=1) <= self.create_date <= now

    def __str__(self):
        return self.group_name

kuhub/models/group_create.py
from django.db import models
from django.contrib.auth.hashers import make_password, check_password

class GroupCreate(models.Model):
    group = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    group_password = models.CharField(max_length=128)

    def set_password(self, raw_password):
        #collect password as hashed password.
        hashed_password = make_password(raw_password)
        self.group_password = hashed_password
        self.save()

    def check_password(self, raw_password):
        #check if the password is right or not.
        return check_password(raw_password, self.group_password)

kuhub/models/group_event.py
from django.db import models
import random
import string
import uuid

class GroupEvent(models.Model):
    group = models.ForeignKey('Group',on_delete=models.CASCADE)
    start_time = models.CharField(max_length=255)
    end_time = models.CharField(max_length=255)
    show_time = models.CharField(max_length=255, blank=True, null=True)
    summary = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    link = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.summary

kuhub/models/group_meeting.py
from django.db import models

class Group_meeting(models.Model):
    group = models.ForeignKey('Group',on_delete=models.CASCADE)
    start_time = models.CharField(max_length=255)
    end_time = models.CharField(max_length=255)
    summary = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    def get_attendies(self):
        return [member.email for member in self.group.group_member.all()]


    def __str__(self):
        return self.summary

kuhub/models/group_password.py
from django.db import models
from django.contrib.auth.hashers import make_password, check_password


class GroupPassword(models.Model):
    """
        A class representing the password for a group in Group Hub.

        Attributes:
            group_password(str): Hashed password for the group.

            set_password(raw_password): Set the group password by hashing the raw password.
            check_password(raw_password): Check if the provided raw password matches the hashed group password.

    """
    group_password = models.CharField(max_length=128)

    def set_password(self, raw_password):
        """
        Set the group password by hashing the raw password.
        """

        # collect password as hashed password.
        hashed_password = make_password(raw_password)
        self.group_password = hashed_password
        self.save()

    def check_password(self, raw_password):
        """
        Check if the provided raw password matches the hashed group password.

        Returns:
            bool: True when the password is correct.
        """
        # check if the password is right or not.
        return check_password(raw_password, self.group_password)

kuhub/models/group_tag.py
"""Import models from django."""
from django.db import models


class GroupTag(models.Model):
    """Class Tag table."""
    tag_text = models.CharField(max_length=200)

    def __str__(self):
        return self.tag_text

kuhub/models/group_tags.py
"""Import models from django."""
from django.db import models


class GroupTags(models.Model):
    """
        Model representing tags associated with groups in Group Hub.

        Attributes:
            tag_text (str): The text representing the tag.
    """
    tag_text = models.CharField(max_length=200)

    def __str__(self):
        return self.tag_text

kuhub/models/note.py
from django.db import models

class Note(models.Model):
    """
        Model representing a note associated with a group in Group Hub.

        Attributes:
            group (Group): ForeignKey to the Group model, specifying the group associated with the note.
            note_text (str): The text content of the note.

    """
    group = models.ForeignKey('Group',on_delete=models.CASCADE)
    note_text = models.CharField(max_length=255)

kuhub/models/post.py
"""Import datetime, models, timezone from django."""
import datetime

from django.db import models
from django.utils import timezone


class Post(models.Model):
    """
    A class representing a user's post.

    Attributes:
        username (auth.User): The user who created the post.
        post_content (str): The content of the post.
        post_date (DateTime): The date and time when the post was created.
        liked (QuerySet): The number of likes the post.
        disliked (QuerySet): The number of dislikes the post.
        tag_id (Tags): The tag associated with the post.
        subject_id (Subject): The subject associated with the post.
        """
    username = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE
    )
    post_content = models.CharField(max_length=200)
    post_date = models.DateTimeField(
        'date posted',
        null=True,
        blank=True
    )
    liked = models.ManyToManyField(
        'auth.User',
        blank=True,
        related_name='likes'
    )
    disliked = models.ManyToManyField(
        'auth.User',
        blank=True,
        related_name='dislikes'
    )
    tag_id = models.ForeignKey(
        'Tags',
        on_delete=models.CASCADE,
        default=1
    )
    subject = models.ForeignKey(
        'Subject',
        on_delete=models.CASCADE,
        blank=True,
        default=1
    )

    def was_published_recently_post(self) -> bool:
        """
        Checks if the post was published recently.

        Returns:
            bool: True if the post was published within the last day.
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.post_date <= now

    def total_likes(self) -> int:
        """Return the total number of likes for a post."""
        return self.liked.all().count()

    def total_dislikes(self) -> int:
        """Return the total number of dislikes for a post."""
        return self.disliked.all().count()

    def like_icon_style(self, user) -> str:
        """Return the style of the like icon when the user clicks the like."""
        if user in self.liked.all():
            return 'fa-solid fa-thumbs-up'
        else:
            return 'far fa-thumbs-up'

    def dislike_icon_style(self, user) -> str:
        """Return the style of the dislike icon when the user clicks the dislike."""
        if user in self.disliked.all():
            return 'fa-solid fa-thumbs-down'
        else:
            return 'far fa-thumbs-down'

    def __str__(self) -> str:
        """Return a string with contain the tag, username, and post content."""
        return self.tag_id.tag_text + ' - ' \
               + str(self.username) + ' - ' \
               + self.post_content

kuhub/models/post_comment.py
"""Import models from django."""
from django.db import models


class PostComment(models.Model):
    """
    A class representing the post's comments

    Attributes:
        post(ForeignKey): Represent id of the post.
        comment(CharField): Content of each comment.
        comment_date(DateTimeField): Date that the comment is published.
    """
    user = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
        default=7
    )
    post_id = models.ForeignKey('Post', on_delete=models.CASCADE)
    comment = models.TextField()
    comment_date = models.DateTimeField(
        'date commented', null=True, blank=True
    )

    def __str__(self):
        return self.comment

kuhub/models/post_comments.py
"""Import models from django."""
from django.db import models


class PostComments(models.Model):
    """
    A class representing the post's comments

    Attributes:
        post_id(Post): Represent id of the post.
        comment(str): Content of each comment.
        comment_date(DateTime): Date that the comment is published.
    """
    username = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
        default=7
    )
    post_id = models.ForeignKey('Post', on_delete=models.CASCADE)
    comment = models.TextField()
    comment_date = models.DateTimeField(
        'date commented', null=True, blank=True
    )

    def __str__(self):
        return self.comment

kuhub/models/profile.py
from django.db import models


class Profile(models.Model):
    """A class represent profile of each user"""
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    biography = models.TextField(blank=True)
    display_photo = models.ImageField(
        null=True,
        blank=True
    )

    def __str__(self):
        return self.user.username

kuhub/models/subject.py
from django.db import models


class Subject(models.Model):
    """
        Model representing a subject or course.

        Attributes:
            course_code (str): The code identifying the course.
            type (str): The type or category of the subject.
            name_eng (str): The English name or title of the subject.
            name_th (str): The Thai name or title of the subject.
            unit (str): The unit or credit hours associated with the subject.
            hour (str): The number of hours the subject spans.
            faculty (str): The faculty or department offering the subject.

        """

    course_code = models.CharField(max_length=10)
    type = models.CharField(max_length=100)
    name_eng = models.CharField(max_length=255)
    name_th = models.CharField(max_length=255)
    unit = models.CharField(max_length=10)
    hour = models.CharField(max_length=10)
    faculty = models.CharField(max_length=255)

kuhub/models/tag.py
"""Import models from django."""
from django.db import models


class Tag(models.Model):
    """Class Tag table."""
    tag_text = models.CharField(max_length=200)

kuhub/forms.py
"""This module contains various forms used throughout the application."""
from django import forms
from kuhub.models import Tags, Subject, Profile, PostComments


class PostForm(forms.Form):
    """From for creating or editing a post."""

    tag_name = forms.ChoiceField(
        label='Tags',
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    subject = forms.ChoiceField(
        label='Subjects',
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    review = forms.CharField(
        widget=forms.Textarea(),
        label='Review',
        required=True
    )

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['tag_name'].choices = [(tag.tag_text, tag.tag_text) for tag in Tags.objects.all()]
        self.fields['subject'].choices = [
            (subject.course_code, subject.course_code + " " + subject.name_eng)
            for subject in Subject.objects.all()
        ]


class ProfileForm(forms.ModelForm):
    """Form is used for creating and editing user profiles."""

    class Meta:
        model = Profile
        fields = ['biography', 'display_photo']


class GroupForm(forms.Form):
    """Form for creating or managing a group."""

    name = forms.CharField(
        widget=forms.Textarea(attrs={'cols': 50, 'rows': 1}),
        label='Group name:',
        required=True
    )
    tag_name = forms.CharField(
        widget=forms.Textarea(attrs={'cols': 70, 'rows': 1}),
        label='Tags :',
        required=False
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={'cols': 100, 'rows': 3}),
        label='Description',
        required=False
    )
    password = forms.CharField(
        widget=forms.PasswordInput,
        label='Password',
        required=False
    )
    password_2 = forms.CharField(
        widget=forms.PasswordInput,
        label='Password',
        required=False
    )


class EventForm(forms.Form):
    """Form for creating or editing events."""

    start_time = forms.DateTimeField(
        widget=forms.TextInput(attrs={'type': 'datetime-local'}),
        label='Start Time',
        required=True
    )
    end_time = forms.DateTimeField(
        widget=forms.TextInput(attrs={'type': 'datetime-local'}),
        label='End Time',
        required=True
    )
    summary = forms.CharField(
        widget=forms.Textarea(attrs={'cols': 50, 'rows': 1}),
        label='Event name:',
        required=True
    )
    location = forms.CharField(
        widget=forms.Textarea(attrs={'cols': 50, 'rows': 1}),
        label='Location:',
        required=True
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={'cols': 70, 'rows': 2}),
        label='Location:',
        required=True
    )
    is_meeting = forms.BooleanField(
        required=False,
        widget=forms.RadioSelect(choices=[(True, 'Generate meet')]),
        initial=False,
    )



class CommentForm(forms.ModelForm):
    """Form is used for creating comments on posts."""
    class Meta:
        model = PostComments
        fields = ['comment']


class ReportForm(forms.Form):
    """Form for submitting report issues or content."""
    reason = forms.CharField(widget=forms.Textarea)

kuhub/templates/kuhub/edit_post.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>Edit Post</title>
{% endblock %}

{% block content %}

<style>
    body {
        background-color: #BFE89C;
    }
</style>

{% load static %}
<link rel="stylesheet" href="{% static 'kuhub/style.css' %}">
<div class="container mt-4" style="font-family: 'Poppins';">
    <h4><span class="badge rounded-pill shadow p-3 d-flex justify-content-center" style="font-family: 'Poppins'; margin-top: 5%; font-weight: normal; background-color: #36816C;">Edit Post</span></h4>
        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="font-family: 'Poppins'">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
</div>

{% if user.is_authenticated and user == post.username %}
    <div class="container mt-4" style="font-family: 'Poppins';">
        <div class="card border border-1 rounded-4">
            <!-- Post Content -->
            <div class="card-header">
                {{ post.tag_id.tag_text }} |
                <a href="{% url 'kuhub:subject_detail' post.subject.course_code %}">{{ post.subject.course_code }} {{ post.subject.name_eng }}</a> |
                <a href="{% url 'kuhub:gen_ed_type_list' %}#{{ post.subject.type|slugify }}">{{ post.subject.type }}</a>
            </div>
            <div class="card-body position-relative">
                <div class="dropdown position-absolute top-0 end-0">
                    <!-- Dropdown Menu -->
                </div>
                <a href="{% url 'kuhub:profile_view' username=post.username %}">
                    {% with profile=post.username.profile %}
                        <div class="d-flex align-items-center">
                            <img class="me-2 rounded-circle" src="{% if profile.display_photo %}{{ profile.display_photo.url }}{% else %}{% static 'kuhub\static\images\default_profile.jpg' %}{% endif %}" width="45" height="45" alt="{{ post.username }}'s Profile">
                            <h4 class="card-title" style="font-weight: 600; margin-bottom: 0;">{{ post.username }}</h4>
                        </div>
                    {% endwith %}
                </a>
                <br>
                <p class="card-text">{{ post.post_content }}</p>
                <h6 class="card-subtitle mb-2 text-muted"><i class="fa-regular fa-clock" style="margin-right: 10px;"></i>{{ post.post_date }}</h6>
            </div>
        </div>

        <!-- Edit form -->
        <form action="{% url 'kuhub:edit_post' post.pk %}" method="post" enctype="multipart/form-data" style="margin-top: 3%;">
            {% csrf_token %}

            <div class="mb-3">
                <label class="form-label">Tags</label>
                <div style="width: 300px;">
                    {{ form.tag_name }}
                </div>
            </div>

            <div class="mb-3">
                <label class="form-label">Subjects</label>
                <div style="width: 500px;">
                    {{ form.subject }}
                </div>
            </div>

            <div class="mb-3">
                <label class="form-label">Edit Content</label>
                <br>
                {{ form.review }}
            </div>

            <div class="mb-3" id="file-upload-container" style="display: none;">
                <label class="form-label">Upload File (.pdf) / Picture (.jpg, .jpeg, .png)</label>
                <input type="file" name="file_upload" id="file-upload-input" class="form-control" accept=".jpg, .jpeg, .png, .pdf">
            </div>
            <div class="submit-btn" style="margin-bottom: 5%; margin-top: 3%;">
                <input type="submit" name="post" id="button_post" value="Update Post" class="btn btn-success">
            </div>
        </form>
    </div>

{% endif %}

<script src="{% static 'kuhub/js/upload-file.js' %}"></script>
{% endblock %}

kuhub/templates/kuhub/review.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>Review-Hub</title>
{% endblock %}


{% block content %}
{% load custom_filters %}
{% load static %}

<style>
    body {
        background-color: #61BDA3;
    }
    .custom-border {
        border-radius: 10px;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        background-color: #C5E7DD;
    }
    .username-section {
        float: right;
        text-align: right;
    }

    .follow-button-section {
        position: absolute;
        top: 0;
        right: 0;
        margin: 10px;
    }
</style>

<div class="container mt-4">
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="font-family: 'Poppins'">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
</div>

<!-- Search box -->
<div class="container mt-4 custom-border shadow-lg" style="font-family: 'Poppins';">
    <form method="get" action="{% url 'kuhub:review' %}">
        <div class="row">
            <div class="col-md-4">
                <label class="form-label"><strong>{{ form.post_content.label }}</strong></label>
                <div class="input-group" style="max-width: 400px;">
                    {{ form.post_content }}
                </div>
            </div>

            <div class="col-md-3">
                <label class="form-label"><strong>{{ form.order_by_liked_disliked.label }}</strong></label>
                <div class="input-group" style="max-width: 200px;">
                    {{ form.order_by_liked_disliked }}
                </div>
            </div>

            <div class="col-md-5">
                <label class="form-label"><strong>{{ form.order_by_post.label }}</strong></label>
                <div class="input-group" style="max-width: 200px;">
                    {{ form.order_by_post }}
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-success" style="padding: 5px 30px;">
                <i class="fa-solid fa-magnifying-glass fa-fade fa-xl"></i>
                <span style="font-family: 'Poppins'">Search</span>
            </button>
        </div>
    </form>
</div>

<!-- Post -->
<div class="container" style="font-family: 'Poppins'">
    {% if posts_list %}
        {% for post in posts_list %}
            <div class="card border border-1 rounded-4">
                <div class="card-header">
                    {% if post.was_published_recently_post %}
                        <span class="badge rounded-pill text-bg-danger" style="text-align: center; margin-right: 5px;">New!</span>
                    {% endif %}
                    {{ post.tag_id.tag_text }} |
                    <a href="{% url 'kuhub:subject_detail' post.subject.course_code %}">{{ post.subject.course_code }} {{ post.subject.name_eng }}</a> |
                    <a href="{% url 'kuhub:gen_ed_type_list' %}#{{ post.subject.type|slugify }}">{{ post.subject.type }}</a>
                </div>
                <div class="card-body position-relative">
                    <div class="dropdown position-absolute top-0 end-0">
                        <button class="btn btn-link kebab-menu" type="button" id="kebabMenu{{ post.pk }}" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-ellipsis-v"></i>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="kebabMenu{{ post.pk }}" style="box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);">
                            {% if user.is_authenticated and post.username == user %}
                                <li><a class="dropdown-item" href="{% url 'kuhub:edit_post' post.pk %}">Edit Post</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'kuhub:report_post' pk=post.pk %}">Report</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <a href="{% url 'kuhub:profile_view' username=post.username %}" style="text-decoration-line: none;">
                        {% with profile=post.username.profile.display_photo %}
                            <div class="d-flex align-items-center">
                                <img class="me-2 rounded-circle" src="{{ profile }}" width="45" height="45" alt="{{ post.username }}'s Profile">
                                <h4 class="card-title" style="font-weight: 550; margin-bottom: 0;">{{ post.username }}</h4>
                            </div>
                        {% endwith %}
                    </a>
                    <br>
                    <p class="card-text">{{ post.post_content }}</p>
                    <h6 class="card-subtitle mb-2 text-muted"><i class="fa-regular fa-clock" style="margin-right: 10px;"></i>{{ post.post_date }}</h6>
                </div>
                <div class="card-footer custom-footer">
                    <div class="button-group">
                        {% if user.is_authenticated %}
                            <button type="button" class="btn btn-link" id="like-btn-{{ post.pk }}" data-content="{{ post.pk }}" onclick="like_button_click('{{ post.pk }}')">
                                <i class="{{ like_icon_styles|index:forloop.counter0 }}"></i>
                            </button>
                            <span id="likes-count-{{ post.pk }}">{{ post.total_likes }}</span>

                            <button type="button" class="btn btn-link" id="dislike-btn-{{post.pk}}" data-content="{{ post.pk }}" onclick="dislike_button_click('{{ post.pk }}')">
                                <i class="{{ dislike_icon_styles|index:forloop.counter0 }}"></i>
                            </button>
                            <span id="dislikes-count-{{ post.pk }}">{{ post.total_dislikes }}</span>


                        {% else %}
                            <form action="{% url 'account_login' %}">
                                <button type="submit" class="btn btn-link">
                                    <i class="fa-regular fa-thumbs-up"></i>
                                </button>
                                <span>{{ post.total_likes }}</span>
                                <button type="submit" class="btn btn-link">
                                    <i class="fa-regular fa-thumbs-down"></i>
                                </button>
                                <span>{{ post.total_dislikes }}</span>
                            </form>
                        {% endif %}
                        <a href="{% url 'kuhub:post_detail' pk=post.pk %}" class="btn btn-link">See comments</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h1>No posts are available.</h1>
    {% endif %}
</div>
{% if user.is_authenticated %}
    <button type="button" id=create_post class="round-create"><a href="{% url 'kuhub:create_post' %}" style="text-decoration: none; color: white;">&#9998;</a></button>
{% endif %}
<link rel="stylesheet" href="{% static 'kuhub/style.css' %}">

<script>
function click_button(postId, response) {
    console.log('Server response:', response);
    let like_count = response.data.likes;
    let dislike_count = response.data.dislikes;
    console.log('Like Count:', like_count);
    console.log('Dislike Count:', dislike_count);
    document.getElementById('likes-count-' + postId).innerText = like_count;
    document.getElementById('dislikes-count-' + postId).innerText = dislike_count;
    document.getElementById('like-btn-' + postId).innerHTML = '<i class="' + response.data.like_style + '"></i>';
    document.getElementById('dislike-btn-' + postId).innerHTML = '<i class="' + response.data.dislike_style + '"></i>';
}


function like_button_click(postId) {
    axios({
        url: '{% url "kuhub:like_post" %}',
        method: 'POST',
        data: {
            'post_id': postId,
        },
        headers: {'X-Requested-With': 'XMLHttpRequest', 'cookie': document.cookie},
        xsrfCookieName: 'csrftoken',
        xsrfHeaderName: 'X-CSRFToken',
        withCredentials: true,
    })
    .then(function (response) {
        click_button(postId, response);
    })
    .catch(function (error) {
        console.log('Error:', error);
    });
}

function dislike_button_click(postId) {
    axios({
        url: '{% url "kuhub:dislike_post" %}',
        method: 'POST',
        data: {
            'post_id': postId,
        },
        headers: {'X-Requested-With': 'XMLHttpRequest', 'cookie': document.cookie},
        xsrfCookieName: 'csrftoken',
        xsrfHeaderName: 'X-CSRFToken',
        withCredentials: true,
    })
    .then(function (response) {
        click_button(postId, response);
    })
    .catch(function (error) {
        console.log('Error:', error);
    });
}

</script>
{% endblock %}